### ISSUE TITLE
HashScan can no longer resolve "kabuto.hh"

### ISSUE THREAD

**Issue by ericleponner** [kabuto-sh/ns#3]
Name resolution seems to be broken in [hashscan.io](https://hashscan.io)

1) Goto https://hashscan.io
2) Type `kabuto.hh` in `Search Bar` and press `Return`
=> `Not Result` page is displayed

In developer console, browser indicates that it gets 404 for the following request:
[https://ns.kabuto.sh/api/name/kabuto.hh/record/address/3030](https://ns.kabuto.sh/api/name/kabuto.hh/record/address/3030)
This request used to work nicely so far.

Same behavior for `example.hh` and `ken.hh`.

**Comment by SharksT** [comment]
Fixed.

**Comment by ericleponner** [comment]
I confirm it's fixed.
Thank you all :)
